{{- if ne .Values.global.env_name "prod" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Developers
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: Developers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: Developers
subjects:
  - kind: Group
    name: Kube-C4-Developers-APP
{{- end}}
---
